language: python
dist: trusty
sudo: true

services:
  - docker

branches:
  only:
    master

script:
  - docker build -t mrtrustworthy/japy:latest .
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
  - docker push "mrtrustworthy/japy:latest
  - helm version


install:
  - sudo apt-get update && sudo apt-get install -y apt-transport-https
  - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list

  - sudo apt-get update
  - sudo apt-get install -y kubectl
  - mkdir ~/.kube
  - echo "$CLUSTER_CONFIG" | base64 -d > ~/.kube/config

  - wget -O helm.tgz https://storage.googleapis.com/kubernetes-helm/helm-v2.12.1-linux-amd64.tar.gz
  - tar -zxvf helm.tgz
  - mv linux-amd64/helm /usr/local/bin/helm
