language: python

services:
  - docker

branches:
  only:
    master

script:
  - docker build -t mrtrustworthy/japy:latest .
  - echo "$DOCKERHUB_PASS" | docker login -u "DOCKERHUB_USER" --password-stdin
  - docker push mrtrustworthy/japy:latest
  - echo "DONE"


