# Default values for japy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mrtrustworthy/japy
  tag: latest
  pullPolicy: Always

japySecrets:
  COOKIE: secure
  DB_DBNAME: secure
  DB_HOST: secure
  DB_PASSWORD: secure
  DB_USER: secure


nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  clusterIp: "10.35.240.200"
  loadBalancerIp: secure
  port: 80



