LETTERS = {
    "Standard": [
        {"vocable": "あ", "syllable": "a"},
        {"vocable": "い", "syllable": "i"},
        {"vocable": "う", "syllable": "u"},
        {"vocable": "え", "syllable": "e"},
        {"vocable": "お", "syllable": "o"},
        {"vocable": "か", "syllable": "ka"},
        {"vocable": "き", "syllable": "ki"},
        {"vocable": "く", "syllable": "ku"},
        {"vocable": "け", "syllable": "ke"},
        {"vocable": "こ", "syllable": "ko"},
        {"vocable": "さ", "syllable": "sa"},
        {"vocable": "し", "syllable": "shi"},
        {"vocable": "す", "syllable": "su"},
        {"vocable": "せ", "syllable": "se"},
        {"vocable": "そ", "syllable": "so"},
        {"vocable": "た", "syllable": "ta"},
        {"vocable": "ち", "syllable": "chi"},
        {"vocable": "つ", "syllable": "tsu"},
        {"vocable": "て", "syllable": "te"},
        {"vocable": "と", "syllable": "to"},
        {"vocable": "な", "syllable": "na"},
        {"vocable": "に", "syllable": "ni"},
        {"vocable": "ぬ", "syllable": "nu"},
        {"vocable": "ね", "syllable": "ne"},
        {"vocable": "の", "syllable": "no"},
        {"vocable": "は", "syllable": "ha"},
        {"vocable": "ひ", "syllable": "hi"},
        {"vocable": "ふ", "syllable": "fu"},
        {"vocable": "へ", "syllable": "he"},
        {"vocable": "ほ", "syllable": "ho"},
        {"vocable": "ま", "syllable": "ma"},
        {"vocable": "み", "syllable": "mi"},
        {"vocable": "む", "syllable": "mu"},
        {"vocable": "め", "syllable": "me"},
        {"vocable": "も", "syllable": "mo"},
        {"vocable": "や", "syllable": "ya"},
        {"vocable": "ゆ", "syllable": "yu"},
        {"vocable": "よ", "syllable": "yo"},
        {"vocable": "ら", "syllable": "ra"},
        {"vocable": "り", "syllable": "ri"},
        {"vocable": "る", "syllable": "ru"},
        {"vocable": "れ", "syllable": "re"},
        {"vocable": "ろ", "syllable": "ro"},
        {"vocable": "わ", "syllable": "wa"},
        {"vocable": "を", "syllable": "wo"},
        {"vocable": "ん", "syllable": "n"},
    ],
    "Diacritics": [
        {"vocable": "が", "syllable": "ga"},
        {"vocable": "ぎ", "syllable": "gi"},
        {"vocable": "ぐ", "syllable": "gu"},
        {"vocable": "げ", "syllable": "ge"},
        {"vocable": "ご", "syllable": "go"},
        {"vocable": "ざ", "syllable": "za"},
        {"vocable": "じ", "syllable": "ji"},
        {"vocable": "ず", "syllable": "zu"},
        {"vocable": "ぜ", "syllable": "ze"},
        {"vocable": "ぞ", "syllable": "zo"},
        {"vocable": "だ", "syllable": "da"},
        {"vocable": "ぢ", "syllable": "ji"},
        {"vocable": "づ", "syllable": "zu"},
        {"vocable": "で", "syllable": "de"},
        {"vocable": "ど", "syllable": "do"},
        {"vocable": "ば", "syllable": "ba"},
        {"vocable": "び", "syllable": "bi"},
        {"vocable": "ぶ", "syllable": "bu"},
        {"vocable": "べ", "syllable": "be"},
        {"vocable": "ぼ", "syllable": "bo"},
        {"vocable": "ぱ", "syllable": "pa"},
        {"vocable": "ぴ", "syllable": "pi"},
        {"vocable": "ぷ", "syllable": "pu"},
        {"vocable": "ぺ", "syllable": "pe"},
        {"vocable": "ぽ", "syllable": "po"},
    ],
    "Diagraphs": [
        {"vocable": "きゃ", "syllable": "kya"},
        {"vocable": "きゅ", "syllable": "kyu"},
        {"vocable": "きょ", "syllable": "kyo"},
        {"vocable": "しゃ", "syllable": "sha"},
        {"vocable": "しゅ", "syllable": "shu"},
        {"vocable": "しょ", "syllable": "sho"},
        {"vocable": "ちゃ", "syllable": "cha"},
        {"vocable": "ちゅ", "syllable": "chu"},
        {"vocable": "ちょ", "syllable": "cho"},
        {"vocable": "にゃ", "syllable": "nya"},
        {"vocable": "にゅ", "syllable": "nyu"},
        {"vocable": "にょ", "syllable": "nyo"},
        {"vocable": "ひゃ", "syllable": "hya"},
        {"vocable": "ひゅ", "syllable": "hyu"},
        {"vocable": "ひょ", "syllable": "hyo"},
        {"vocable": "みゃ", "syllable": "mya"},
        {"vocable": "みゅ", "syllable": "myu"},
        {"vocable": "みょ", "syllable": "myo"},
        {"vocable": "りゃ", "syllable": "rya"},
        {"vocable": "りゅ", "syllable": "ryu"},
        {"vocable": "りょ", "syllable": "ryo"},
    ],
    "Diacritic digraphs": [
        {"vocable": "ぎゃ", "syllable": "gya"},
        {"vocable": "ぎゅ", "syllable": "gyu"},
        {"vocable": "ぎょ", "syllable": "gyo"},
        {"vocable": "じゃ", "syllable": "ja"},
        {"vocable": "じゅ", "syllable": "ju"},
        {"vocable": "じょ", "syllable": "jo"},
        {"vocable": "ぢゃ", "syllable": "ja"},
        {"vocable": "ぢゅ", "syllable": "ju"},
        {"vocable": "ぢょ", "syllable": "jo"},
        {"vocable": "びゃ", "syllable": "bya"},
        {"vocable": "びゅ", "syllable": "byu"},
        {"vocable": "びょ", "syllable": "byo"},
        {"vocable": "ぴゃ", "syllable": "pya"},
        {"vocable": "ぴゅ", "syllable": "pyu"},
        {"vocable": "ぴょ", "syllable": "pyo"}
    ]
}
LETTER_SETS = list(LETTERS.keys())
