apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "japy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "japy.name" . }}
    helm.sh/chart: {{ include "japy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "japy.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "japy.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: COOKIE
              value: {{ .Values.japyEnvironmentVariables.COOKIE }}
            - name: DB_DBNAME
              value: {{ .Values.japyEnvironmentVariables.DB_DBNAME }}
            - name: DB_HOST
              value: {{ .Values.japyEnvironmentVariables.DB_HOST }}
            - name: DB_PASSWORD
              value: {{ .Values.japyEnvironmentVariables.DB_PASSWORD }}
            - name: DB_USER
              value: {{ .Values.japyEnvironmentVariables.DB_USER }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
